config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords],controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    root to:'homes#top'
    resource :user, only: [:show, :edit, :update]
    get'user/quit'=>  'users#quit',as: 'quit'
    patch 'user/out'=> 'users#out', as: 'out'
    get 'user/favorite' => 'users#favorite', as: 'favorite'
    post 'users/guest_login' => 'guest_sessions#create'
    get 'properties/map/:property_id'=>  'properties#map', as: 'map'
    get 'properties/search'=>  'properties#search', as: 'search'#違うURLで同じアクションに飛びたい時は二つかかず一つにルーティングをまとめる idはどうするかというとtophtmlの方で分岐させる
    resources :properties,only:[:show, :index] do
      resources :contacts,only:[:new, :create, :show]
      resource :favorites, only: [:create, :destroy]
      resources :rules, only: [:create]
      resources :reviews, only: [:create]
      resources :questions, only: [:create]
    end
    resources :histories, only: [:index, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :questions do
      resources :comments, only: [:create]
    end
    resources :comments do
      resources :comment_comments, only: [:create]
    end
  end

  namespace :admin do
    resources :users,only:[:index, :show, :edit, :update]
    resources :reviews,only:[:index, :destroy]
    resources :questions,only:[:index, :destroy]
    resources :comments,only: [:destroy]
    resources :comment_comments,only: [:destroy]
    resources :contacts,only:[:index, :show]
    resources :rules,only:[:index, :destroy]
  end
end

app/models/rule.rb
class Rule < ApplicationRecord
   belongs_to :user
   belongs_to :property

   validates :body, presence: true
end

app/controllers/admin/rules_controller.rb
class Admin::RulesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @rules_count = Rule.all.count
    @rules = Rule.page(params[:page]).per(15)
  end

  def destroy
    @rule=Rule.find(params[:id])
    @rule.destroy
    redirect_to admin_rules_path
  end
end

app/controllers/user/rules_controller.rb
class User::RulesController < ApplicationController
  before_action :authenticate_user!
  def create
    @rule = Rule.new(rule_params)
    @rule.user_id = current_user.id
    @rule.property_id = params[:property_id]
    if @rule.save
      redirect_to property_path(@rule.property_id, :flag => "rl")
    else
      @property=Property.find(params[:property_id])
      @review = Review.new
      @reviews=@property.reviews
      @question = Question.new
      @questions = @property.questions
      @comment = Comment.new
      @comment_comment = CommentComment.new
      @rules = @property.rules
      @avg_score = Review.where(property_id: @property.id).average(:score)
      render 'user/properties/show'
    end
  end

  private

  def rule_params
    params.require(:rule).permit(:body)
  end
end

app/helpers/admin/rules_helper.rb
module Admin::RulesHelper
end

app/helpers/user/rule_helper.rb
module User::RuleHelper
end

app/helpers/user/rules_helper.rb
module User::RulesHelper
end

app/views/admin/rules/index.html.erb
<h4 class="ml-3 mt-5">ハウスルール一覧</h4>
<% if @rules.present? %>
  <div class="ml-3 mt-4">全<%= @rules_count %>件</div>
  <% @rules.each do |rule| %>
    <div class="container mt-5">
      <div class="row mb-2">
        <div class="col-6">
          <%= link_to property_path(rule.property.id) do %>
            <h6><%= rule.property.property_name %></h6>
          <%end%>
          <div class="writing">
            ・<%= rule.body %>
          </div>
        </div>
        <div class="col-6">
          <span class="mr-2"><%= link_to "削除", admin_rule_path(rule.id), method: :delete %></span>
          <%= link_to admin_user_path(rule.user.id) do %>
            <%= rule.user.nickname %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="pagination"><%= paginate @rules, theme: 'twitter-bootstrap-4' %></div>
<% end %>