config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords],controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    root to:'homes#top'
    resource :user, only: [:show, :edit, :update]
    get'user/quit'=>  'users#quit',as: 'quit'
    patch 'user/out'=> 'users#out', as: 'out'
    get 'user/favorite' => 'users#favorite', as: 'favorite'
    post 'users/guest_login' => 'guest_sessions#create'
    get 'properties/map/:property_id'=>  'properties#map', as: 'map'
    get 'properties/search'=>  'properties#search', as: 'search'#違うURLで同じアクションに飛びたい時は二つかかず一つにルーティングをまとめる idはどうするかというとtophtmlの方で分岐させる
    resources :properties,only:[:show, :index] do
      resources :contacts,only:[:new, :create, :show]
      resource :favorites, only: [:create, :destroy]
      resources :rules, only: [:create]
      resources :reviews, only: [:create]
      resources :questions, only: [:create]
    end
    resources :histories, only: [:index, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :questions do
      resources :comments, only: [:create]
    end
    resources :comments do
      resources :comment_comments, only: [:create]
    end
  end

  namespace :admin do
    resources :users,only:[:index, :show, :edit, :update]
    resources :reviews,only:[:index, :destroy]
    resources :questions,only:[:index, :destroy]
    resources :comments,only: [:destroy]
    resources :comment_comments,only: [:destroy]
    resources :contacts,only:[:index, :show]
    resources :rules,only:[:index, :destroy]
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @reviews_count = Review.all.count
    @reviews = Review.page(params[:page]).per(15)
  end

  def destroy
    @review=Review.find(params[:id])
    @review.destroy
    redirect_to admin_reviews_path
  end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def create
    relation_detail=""
    if review_params[:relation] == "former_resident"
      relation_detail = review_params[:relation_detail1]
    else
      relation_detail = review_params[:relation_detail2]
    end
    review_params_copy = review_params.clone
    review_params_copy.delete(:relation_detail1)
    review_params_copy.delete(:relation_detail2)
    review_params_copy[:relation_detail] = relation_detail

    @review = Review.new(review_params_copy)
    if @review.relation == "resident"
      @review.relation_detail = "now_resident"
    end

    @review.user_id = current_user.id
    @review.property_id = params[:property_id]

    if @review.save
      flash[:notice] = "レビューの投稿が完了しました!"
      redirect_to property_path(params[:property_id])
    else
      @property=Property.find(params[:property_id])
      @reviews=@property.reviews
      @question = Question.new
      @questions = @property.questions
      @comment = Comment.new
      @comment_comment = CommentComment.new
      @rule = Rule.new
      @rules = @property.rules
      @avg_score = Review.where(property_id: @property.id).average(:score)
      render 'user/properties/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :body, :relation, :relation_detail1, :relation_detail2, :score, :atmosphere, :cleanliness_shared, :congestion_shared, :noise, :distance_sense, :net_speed, :shower, :event, :repeat)
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<h4 class="ml-3 mt-5">レビュー一覧</h4>
<% if @reviews.present? %>
  <div class="ml-3 mt-4">全<%= @reviews_count %>件</div>
  <% @reviews.each do |review| %>
    <div class="container mt-5">
      <div class="row mb-2">
        <div class="col-6">
          <%= link_to property_path(review.property.id) do %>
            <h6><%= review.property.property_name %></h6>
          <% end %>
          <div class="writing">
            <div class="mb-2"><%= review.title %></div>
            <%= review.body %>
          </div>
        </div>
        <div class="col-6">
          <span class="mr-2"><%= link_to "削除", admin_review_path(review.id), method: :delete %></span>
          <%= link_to admin_user_path(review.user.id) do %>
            <%= review.user.nickname %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="pagination"><%= paginate @reviews, theme: 'twitter-bootstrap-4' %></div>
<% end %>