config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords],controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    root to:'homes#top'
    resource :user, only: [:show, :edit, :update]
    get'user/quit'=>  'users#quit',as: 'quit'
    patch 'user/out'=> 'users#out', as: 'out'
    get 'user/favorite' => 'users#favorite', as: 'favorite'
    post 'users/guest_login' => 'guest_sessions#create'
    get 'properties/map/:property_id'=>  'properties#map', as: 'map'
    get 'properties/search'=>  'properties#search', as: 'search'#違うURLで同じアクションに飛びたい時は二つかかず一つにルーティングをまとめる idはどうするかというとtophtmlの方で分岐させる
    resources :properties,only:[:show, :index] do
      resources :contacts,only:[:new, :create, :show]
      resource :favorites, only: [:create, :destroy]
      resources :rules, only: [:create]
      resources :reviews, only: [:create]
      resources :questions, only: [:create]
    end
    resources :histories, only: [:index, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :questions do
      resources :comments, only: [:create]
    end
    resources :comments do
      resources :comment_comments, only: [:create]
    end
  end

  namespace :admin do
    resources :users,only:[:index, :show, :edit, :update]
    resources :reviews,only:[:index, :destroy]
    resources :questions,only:[:index, :destroy]
    resources :comments,only: [:destroy]
    resources :comment_comments,only: [:destroy]
    resources :contacts,only:[:index, :show]
    resources :rules,only:[:index, :destroy]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users_count = User.all.count
    @users = User.page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :age, :gender, :email, :is_deleted)
  end
end

app/controllers/user/comment_comments_controller.rb
class User::CommentCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment_comment = CommentComment.new(comment_comment_params)
    @comment_comment.user_id = current_user .id
    @comment_comment.comment_id = params[:comment_id]
    comment = Comment.find(params[:comment_id])
    question = Question.find(comment.question_id)
    if @comment_comment.save
      #コメントに対してのコメントしてくれた人に通知する処理
      @notification = Notification.new
      #コメントに対してのコメント
      @notification.action = "reply_on_comment"
      @notification.comment_id = params[:comment_id]
      @notification.sender_id = @comment_comment.user_id
      @notification.receiver_id = comment.user_id
      @notification.checked = false
      @notification.property_id = question.property_id
      @notification.save
      redirect_to property_path(question.property_id, flag: "qa")
    else
      @property=Property.find(question.property_id)
      @review = Review.new
      @question = Question.new
      @reviews=@property.reviews
      @questions = @property.questions
      @comment = Comment.new
      @rule = Rule.new
      @rules = @property.rules
      @avg_score = Review.where(property_id: @property.id).average(:score)
      render 'user/properties/show'
    end
  end

  private

  def comment_comment_params
      params.require(:comment_comment).permit(:body, :relation)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.question_id = params[:question_id]
    question = Question.find(params[:question_id])
    if @comment.save
    #質問に対して回答してくれた人に通知する処理
      @notification = Notification.new
      #質問に対しての回答
      @notification.action = "comment_on_question"
      @notification.sender_id = @comment.user_id
      @notification.receiver_id = question.user_id
      @notification.checked = false
      @notification.property_id = @comment.question.property_id
      @notification.save!
      redirect_to property_path(@comment.question.property_id, :flag => "qa")
    else
      @property=Property.find(question.property_id)
      @review = Review.new
      @reviews=@property.reviews
      @question = Question.new
      @questions = @property.questions
      @comment_comment = CommentComment.new
      @rule = Rule.new
      @rules = @property.rules
      @avg_score = Review.where(property_id: @property.id).average(:score)
      render 'user/properties/show'
    end
  end

  private

  def comment_params
      params.require(:comment).permit(:body, :relation, :comment_id)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  before_action :authenticate_user!

  def new
    @property=Property.find(params[:property_id])
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    @contact.property_id = params[:property_id]
    if  @contact.save
      flash[:notice] = "お問い合わせの送信が完了しました!"
      redirect_to root_path
    else
      @property=Property.find(params[:property_id])
       render :new
    end
  end

  def show
    @property=Property.find(params[:property_id]) #serach画面の物件選ぶみたいに選んでないんだからidは取れない
    @contact = @property.Contact.find(params[:id])
  end

  private

  def contact_params
      params.require(:contact).permit(:name, :name_kana, :gender, :age, :nationality, :email, :telephone_number, :address, :occupation, :schedule, :hope, :contact)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    property = Property.find(params[:property_id])
    favorite = current_user.favorites.new(property_id: property.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
     property = Property.find(params[:property_id])
    favorite = current_user.favorites.find_by(property_id: property.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/user/guest_sessions_controller.rb
class User::GuestSessionsController < ApplicationController
before_action :authenticate_user!, except: [:create]

  def create
    user = User.find_or_create_by(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "ゲストユーザー"
      user.age ="非公開"
      user.gender ="非公開"
    end
    sign_in user
    session[:user_id] = user.id
    flash[:notice] = "ゲストユーザーとしてログインしました"
    redirect_to root_path
  end
end

app/controllers/user/histories_controller.rb
class User::HistoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @histories_count = current_user.histories.count
    @histories = current_user.histories.page(params[:page]).per(20)
  end

  def destroy
    @history = History.find(params[:id])
    @history.destroy
    redirect_to request.referer
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  before_action :set_tags

  def top
    @area_groups = AreaGroup.all

    #ラジオボタンレビュー項目の平均点を物件ごとに算出して上位5件を表示
    @properties_atmosphere = Property.popular_ranking('atmosphere', 5)
    @properties_noise = Property.popular_ranking('noise', 5)
    @properties_cleanliness_shared = Property.popular_ranking('cleanliness_shared', 5)
    @properties_congestion_shared = Property.popular_ranking('congestion_shared', 5)
    #各物件のお気入り数が多い物件上位5件を表示
    @properties_favorites = Property.many_favorite.first(5)
  end
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    current_user.passive_notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy
    Notification.find(params[:id]).destroy
    redirect_to notifications_path
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/properties_controller.rb
class User::PropertiesController < ApplicationController
  before_action :authenticate_user!, except: [:search, :index]
  before_action :set_tags

  def search
    #topページの検索の場合
    if params[:from_top].present?
      @area_groups = params[:area_group_id]
      @tags = if params[:tag_id].present?#三項演算子
                [params[:tag_id].to_i]
              else
                nil
              end
      #@tags =params[:tag_id].present? ? [params[:tag_id].to_i] : nil

    else
      #複数検索の場合
      @areas = []
      if params[:area_id].present?
        @areas = params[:area_id].reject(&:empty?)
      end
      @tags = []
      if ! params[:tag_id].nil?
        params[:tag_id].reject(&:empty?).each do |id|
          if (id != "")
            @tags.push(id.to_i)
          end
        end
      end
    end


    # 未入力の場合全件が対象
    @properties = Property.all
    # エリア関連の検索処理
    @checkd_areas = []
    if !@areas.blank?
      @properties = @properties.where(area_id: @areas)
      @checkd_areas = @areas
    elsif !@area_groups.blank? && @tags.blank?
      @properties = @properties.where(area_group_id: @area_groups)
      @checkd_areas = Area.where(area_group_id: @area_groups).ids
    end

    if !@tags.blank?
      property_ids = @properties.pluck(:id)
      @tags.each do | tag_id |
        property_ids = Property.joins(:tags).where(id: property_ids).where(tags: {id: tag_id}).pluck(:id)
      end
      @properties = Property.where(id: property_ids)
    end

    # 金額の条件
    if (params[:lower_rent] && !params[:lower_rent].to_i.zero?) && (params[:upper_rent] && !params[:upper_rent].to_i.zero?)#ボッチ演算子
      @properties = @properties.where(rent: params[:lower_rent].to_i..params[:upper_rent].to_i)
    elsif (params[:lower_rent] && params[:lower_rent].to_i.zero?) && (params[:upper_rent] && !params[:upper_rent].to_i.zero?)
      @properties = @properties.where(rent: ..params[:upper_rent].to_i)
    elsif (params[:lower_rent] && !params[:lower_rent].to_i.zero?) && (params[:upper_rent] && params[:upper_rent].to_i.zero?)
      @properties = @properties.where(rent: params[:lower_rent].to_i..)
    end
    @properties_count = @properties.count
    @properties = @properties.page(params[:page]).per(10)

    #検索条件を検索希望一覧画面で表示するため
    @tag_list = Tag.where(id: @tags)
    @area_list = Area.where(id: @areas)
    @area_group_list = AreaGroup.where(id: @area_groups)

    if params[:lower_rent]
      @display_lower_amount =  params[:lower_rent].slice(0,  params[:lower_rent].length - 4)
    end
    if params[:upper_rent]
      @display_upper_amount =  params[:upper_rent].slice(0,  params[:upper_rent].length - 4)
    end

    #再検索用
    @tags=Tag.all

    #キーワード検索の処理
    @keyword = params[:keyword]
    if !@keyword.blank?
      @properties= Property.where("access LIKE ?", "%#{params[:keyword]}%")#モデルでスコープで書く
      .or(Property.where("address LIKE ?", "%#{params[:keyword]}%"))
      .or(Property.where("rent LIKE ?", "%#{params[:keyword]}%"))
      .or(Property.where("property_name LIKE ?", "%#{params[:keyword]}%"))

      @properties_count = @properties.count
      @properties = @properties.page(params[:page]).per(10)

      @checkd_areas = Area.where("area_name LIKE ?", "#{params[:keyword]}%").pluck(:id)
    end
  end

  def index
  end

  def show
    @property=Property.find(params[:id])
    #閲覧履歴
    history = @property.histories.new
    history.user_id = current_user.id
    if current_user.histories.exists?(property_id: "#{params[:id]}")
      old_history = current_user.histories.find_by(property_id: "#{params[:id]}")
      old_history.destroy
    end
    history.save

    @review = Review.new
    @reviews=@property.reviews
    @question = Question.new
    @questions = @property.questions
    @comment = Comment.new
    @comment_comment = CommentComment.new
    @rule = Rule.new
    @rules = @property.rules

    #星評価の平均点を算出
    @avg_score = Review.where(property_id: params[:id]).average(:score)
  end

  def map
    @property=Property.find(params[:property_id])
  end
end

app/controllers/user/questions_controller.rb
class User::QuestionsController < ApplicationController
  before_action :authenticate_user!

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    @question.property_id = params[:property_id]
    @question.checked = false
    if @question.save
      flash[:notice] = "質問の投稿が完了しました!"
    #A物件をレビューしたuser一覧が入っているA物件をレビューした人みんなに通知したいから
      review_users = @question.property.reviews.map{|review| review.user}.uniq
    #レビューしてくれた人一人ひとりにに通知をする処理
      review_users.each do |review_user|
        notification = Notification.new
        notification.action = "review_on_question"
        notification.sender_id = @question.user_id
        notification.receiver_id = review_user.id
        notification.checked = false
        notification.property_id = @question.property_id
        notification.save!
      end
      redirect_to property_path(params[:property_id])
    else
      @property=Property.find(params[:property_id])
      @review = Review.new
      @reviews=@property.reviews
      @questions = @property.questions
      @comment = Comment.new
      @comment_comment = CommentComment.new
      @rule = Rule.new
      @rules = @property.rules
      @avg_score = Review.where(property_id: @property.id).average(:score)
      render 'user/properties/show'
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :relation)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:gender,:age])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    stored_location_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/users/edit.html.erb
<%= form_with model: @user,url: user_path, method: :patch do |f| %>
  <div class="container">
    <div class="row mb-2">
      <div class="col-xl-2 mt-5">
        <%= f.label :nickname,"ニックネーム" %>
      </div>
      <div class="col-xl-9 nickname small-nickname">
        <%= f.text_field :nickname %>
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-xl-2">
        <%= f.label :age,"年齢" %>
      </div>
      <div class="col-xl-9">
        <%= f.select :age, [['10代','10代'], ['20代', '20代'], ['30代', '30代'], ['40代','40代'], ['50代','50代'], ['60代','60代'], ['70代','70代'],['非公開','非公開']] %> <!--ageをinteger型じゃなくてstring型にして['20代', "20代"]でもいい-->
      </div>
    </div>
    <div class="row mb-2">
      <div class="col-xl-2">
        <%= f.label :gender,"性別" %>
      </div>
      <div class="col-xl-9">
        <%= f.radio_button :gender, "男性" %>男
        <%= f.radio_button :gender, "女性", class: "ml-3" %>女
        <%= f.radio_button :gender, "非公開" , class: "ml-3" %>非公開
      </div>
    </div>
    <div class="change mb-3">
      <%= f.submit "変更する", class: "btn" %>
    </div>
  </div>
<%end%>

<%= link_to "退会する",quit_path %>

app/views/user/users/favorite.html.erb
<h3 class="mt-4">お気に入り</h3>
<% if @favorites.present? %>
  <h5 class="text-left mt-4">全<%= @favorites_count %>件</h5>
  <% @favorites.each do |favorite| %>
    <div class="row">
      <div class="col-xl-3 mt-3">
        <h5 class="font-weight-bold"><%= favorite.property.property_name %></h5>
        <%= image_tag favorite.property.images[0],size: '230x150' %>
      </div>
      <div class="col-xl-4 mt-5">
        <div class="point">
          <div class="row">
            <div class="col-3">
              <h6 class="favorite ml-2">賃料</h6>
            </div>
            <div class="col-9 mt-1 favorite-explanation">
              <%= favorite.property.rent %>円
            </div>
          </div>
          <div class="row">
            <div class="col-3">
              <h6 class="favorite ml-2">住所</h6>
            </div>
            <div class="col-9 mt-1 favorite-explanation">
              <%= favorite.property.address %>
            </div>
          </div>
          <div class="row">
            <div class="col-3">
              <h6 class="favorite ml-2">アクセス</h6>
            </div>
            <div class="col-9 mt-1 favorite-explanation">
              <%= favorite.property.access %>
            </div>
          </div>
          <div class="row">
            <div class="col-3">
              <h6 class="favorite ml-2">入居条件</h6>
            </div>
            <div class="col-9 mt-1 favorite-explanation">
              <%= favorite.property.condition %>
            </div>
          </div>
          <div class="row">
            <div class="col-3">
              <h6 class="favorite ml-2">空室</h6>
            </div>
            <div class="col-9 mt-1 favorite-explanation">
              <%= favorite.property.vacancy %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xl-1 col-3 mb-5 mt-3">
        <%= link_to property_path(favorite.property.id),class: "btn" do %>
          <p class="favorite-btn ">詳細</p>
        <% end %>
      </div>
      <div class="col-xl-2 col-6 mt-3">
        <%= link_to property_favorites_path(favorite.property.id), method: :delete, class: "btn" do %>
          <p class="favorite-btn">お気に入りから消す</p>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="pagination"><%= paginate @favorites, theme: 'twitter-bootstrap-4' %></div>
<% else %>
  <h6 class="mt-4">お気に入りがありません</h6>
<% end %>

app/views/user/users/quit.html.erb
<p class="mt-5">本当に退会しますか?</p>
<p class="mb-3">※退会するとこれまで投稿した口コミや質問などすべて削除されます</p>
<span class="mr-5"><%= link_to "退会しない",user_path %></span>
<%= link_to"退会する", out_path, method: :patch, "data-confirm" => "OKを押すと退会処理がされます。本当によろしいですか？" %>

app/views/user/users/show.html.erb
<h3 class="mt-4">マイページ</h3>
<div class="row">
  <div class="col-xl-2 col-4 mt-2">
    <p><%= @user.nickname %></p>
    <p><%= @user.age %></p>
    <p><%= @user.gender %></p>
  </div>
  <div class="col-xl-3 col-8 edit">
    <%= link_to "編集する",edit_user_path,class: "btn" %>
  </div>
</div>

<div class="wrap">
  <ul id="tab-menu" class="small-tab-menu">
    <li><a href="#tab1" class="active ">口コミ</a></li>
    <li><a href="#tab2" class="">質問</a></li>
    <li><a href="#tab3" class="">回答</a></li>
    <li><a href="#tab4" class="">コメント</a></li>
    <li><a href="#tab5" class="">ハウスルール</a></li>
    <li><a href="#tab6" class="">お問い合わせ</a></li>
  </ul>
</div>

<div id="tab-contents">
  <div id="tab1" class="tab">
    <% if @reviews.present? %>
      <h5 class="mb-5">全<%=@reviews.count %>件</h5>
      <% @reviews.each do |review| %>
        <%= link_to property_path(review.property.id) do %>
          <div class="user-property font-weight-bold"><%= review.property.property_name %></div>
        <% end %>
        <div class="mb-5">
          <p class="mb-3"><%= review.title %></p>
          <p class="mb-4"><%= review.body %></p>
          <%= render '/user/properties/review', review: review %>
        </div>
      <% end %>
    <% else %>
      <h6 class="mt-4">投稿した口コミがありません</h6>
    <% end %>
  </div>

  <div id="tab2" class="tab">
    <% if @questions.present? %>
      <h5>全<%= @questions.count %>件</h5>
      <% @questions.each do |question| %>
        <%= link_to property_path(question.property.id) do %>
          <div class="user-property user-q font-weight-bold"><%= question.property.property_name %></div>
        <%end%>
        <%= render 'user/properties/question', question: question, comment: @comment,comment_comment: @comment_comment %>
      <% end %>
    <% else %>
      <h6 class="mt-4">投稿した質問がありません</h6>
    <% end %>
  </div>

  <div id="tab3" class="tab">
    <% if @comment_questions.present? %>
      <h5>全<%= @comments.count %>件</h5>
      <% @comment_questions.each do |comment_question| %>
        <%= link_to property_path(comment_question.property.id) do %>
          <div class="user-property user-q font-weight-bold"><%= comment_question.property.property_name %></div>
        <%end%>
        <%= render 'user/properties/question', question: comment_question, comment: @comment, comment_comment: @comment_comment %>
      <% end %>
    <% else %>
      <h6 class="mt-4">投稿した回答がありません</h6>
    <% end %>
  </div>

  <div id="tab4" class="tab">
    <% if @comment_comment_questions.present? %>
      <h5>全<%= @comment_comments.count %>件</h5>
      <% @comment_comment_questions.each do |comment_comment_question| %>
        <%= link_to property_path(comment_comment_question.property.id) do %>
          <div class="user-property user-q font-weight-bold"><%= comment_comment_question.property.property_name %></div>
        <%end%>
        <%= render 'user/properties/question', question: comment_comment_question, comment: @comment, comment_comment: @comment_comment %>
      <% end %>
    <% else %>
      <h6 class="mt-4">投稿したコメントがありません</h6>
    <% end %>
  </div>

  <div id="tab5" class="tab">
    <% if @property_rules.present? %>
      <div class="rule rule01 small-rule">
        <h3 class="text-center">シェアしたハウスルール</h3>
        <% @property_rules.each do |property| %>
          <%= link_to property_path(property.id) do %>
            <div class="user-property-rule mt-4 ml-2"><%= property.property_name %></div>
          <%end%>
          <% property.rules.where(user: current_user).each do |rule| %>
            <p class="mb-3">• <%= rule.body %></p>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <h6 class="mt-4">投稿したハウスルールがありません</h6>
    <% end %>
  </div>

  <div id="tab6" class="tab">
    <% if @contacts.present? %>
      <h5 class="mb-5">全<%= @contacts.count %>件</h5>
      <h4 class="mt-5">お問い合わせ内容</h4>
      <% @contacts.each do |contact| %>
        <%= render 'user/contacts/contact', contact: contact %>
      <%end%>
    <% else %>
      <h6 class="mt-4">お問い合わせがありません</h6>
    <% end %>
  </div>
</div>