config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords],controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: :user do
    root to:'homes#top'
    resource :user, only: [:show, :edit, :update]
    get'user/quit'=>  'users#quit',as: 'quit'
    patch 'user/out'=> 'users#out', as: 'out'
    get 'user/favorite' => 'users#favorite', as: 'favorite'
    post 'users/guest_login' => 'guest_sessions#create'
    get 'properties/map/:property_id'=>  'properties#map', as: 'map'
    get 'properties/search'=>  'properties#search', as: 'search'#違うURLで同じアクションに飛びたい時は二つかかず一つにルーティングをまとめる idはどうするかというとtophtmlの方で分岐させる
    resources :properties,only:[:show, :index] do
      resources :contacts,only:[:new, :create, :show]
      resource :favorites, only: [:create, :destroy]
      resources :rules, only: [:create]
      resources :reviews, only: [:create]
      resources :questions, only: [:create]
    end
    resources :histories, only: [:index, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :questions do
      resources :comments, only: [:create]
    end
    resources :comments do
      resources :comment_comments, only: [:create]
    end
  end

  namespace :admin do
    resources :users,only:[:index, :show, :edit, :update]
    resources :reviews,only:[:index, :destroy]
    resources :questions,only:[:index, :destroy]
    resources :comments,only: [:destroy]
    resources :comment_comments,only: [:destroy]
    resources :contacts,only:[:index, :show]
    resources :rules,only:[:index, :destroy]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users_count = User.all.count
    @users = User.page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :age, :gender, :email, :is_deleted)
  end
end

app/controllers/user/comment_comments_controller.rb
class User::CommentCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment_comment = CommentComment.new(comment_comment_params)
    @comment_comment.user_id = current_user .id
    @comment_comment.comment_id = params[:comment_id]
    comment = Comment.find(params[:comment_id])
    question = Question.find(comment.question_id)
    if @comment_comment.save
      #コメントに対してのコメントしてくれた人に通知する処理
      @notification = Notification.new
      #コメントに対してのコメント
      @notification.action = "reply_on_comment"
      @notification.comment_id = params[:comment_id]
      @notification.sender_id = @comment_comment.user_id
      @notification.receiver_id = comment.user_id
      @notification.checked = false
      @notification.property_id = question.property_id
      @notification.save
      redirect_to property_path(question.property_id, flag: "qa")
    else
      @property=Property.find(question.property_id)
      @review = Review.new
      @question = Question.new
      @reviews=@property.reviews
      @questions = @property.questions
      @comment = Comment.new
      @rule = Rule.new
      @rules = @property.rules
      @avg_score = Review.where(property_id: @property.id).average(:score)
      render 'user/properties/show'
    end
  end

  private

  def comment_comment_params
      params.require(:comment_comment).permit(:body, :relation)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.question_id = params[:question_id]
    question = Question.find(params[:question_id])
    if @comment.save
    #質問に対して回答してくれた人に通知する処理
      @notification = Notification.new
      #質問に対しての回答
      @notification.action = "comment_on_question"
      @notification.sender_id = @comment.user_id
      @notification.receiver_id = question.user_id
      @notification.checked = false
      @notification.property_id = @comment.question.property_id
      @notification.save!
      redirect_to property_path(@comment.question.property_id, :flag => "qa")
    else
      @property=Property.find(question.property_id)
      @review = Review.new
      @reviews=@property.reviews
      @question = Question.new
      @questions = @property.questions
      @comment_comment = CommentComment.new
      @rule = Rule.new
      @rules = @property.rules
      @avg_score = Review.where(property_id: @property.id).average(:score)
      render 'user/properties/show'
    end
  end

  private

  def comment_params
      params.require(:comment).permit(:body, :relation, :comment_id)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  before_action :authenticate_user!

  def new
    @property=Property.find(params[:property_id])
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    @contact.property_id = params[:property_id]
    if  @contact.save
      flash[:notice] = "お問い合わせの送信が完了しました!"
      redirect_to root_path
    else
      @property=Property.find(params[:property_id])
       render :new
    end
  end

  def show
    @property=Property.find(params[:property_id]) #serach画面の物件選ぶみたいに選んでないんだからidは取れない
    @contact = @property.Contact.find(params[:id])
  end

  private

  def contact_params
      params.require(:contact).permit(:name, :name_kana, :gender, :age, :nationality, :email, :telephone_number, :address, :occupation, :schedule, :hope, :contact)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    property = Property.find(params[:property_id])
    favorite = current_user.favorites.new(property_id: property.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
     property = Property.find(params[:property_id])
    favorite = current_user.favorites.find_by(property_id: property.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/user/guest_sessions_controller.rb
class User::GuestSessionsController < ApplicationController
before_action :authenticate_user!, except: [:create]

  def create
    user = User.find_or_create_by(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "ゲストユーザー"
      user.age ="非公開"
      user.gender ="非公開"
    end
    sign_in user
    session[:user_id] = user.id
    flash[:notice] = "ゲストユーザーとしてログインしました"
    redirect_to root_path
  end
end

app/controllers/user/histories_controller.rb
class User::HistoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @histories_count = current_user.histories.count
    @histories = current_user.histories.page(params[:page]).per(20)
  end

  def destroy
    @history = History.find(params[:id])
    @history.destroy
    redirect_to request.referer
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  before_action :set_tags

  def top
    @area_groups = AreaGroup.all

    #ラジオボタンレビュー項目の平均点を物件ごとに算出して上位5件を表示
    @properties_atmosphere = Property.popular_ranking('atmosphere', 5)
    @properties_noise = Property.popular_ranking('noise', 5)
    @properties_cleanliness_shared = Property.popular_ranking('cleanliness_shared', 5)
    @properties_congestion_shared = Property.popular_ranking('congestion_shared', 5)
    #各物件のお気入り数が多い物件上位5件を表示
    @properties_favorites = Property.many_favorite.first(5)
  end
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    current_user.passive_notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy
    Notification.find(params[:id]).destroy
    redirect_to notifications_path
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/properties_controller.rb
class User::PropertiesController < ApplicationController
  before_action :authenticate_user!, except: [:search, :index]
  before_action :set_tags

  def search
    #topページの検索の場合
    if params[:from_top].present?
      @area_groups = params[:area_group_id]
      @tags = if params[:tag_id].present?#三項演算子
                [params[:tag_id].to_i]
              else
                nil
              end
      #@tags =params[:tag_id].present? ? [params[:tag_id].to_i] : nil

    else
      #複数検索の場合
      @areas = []
      if params[:area_id].present?
        @areas = params[:area_id].reject(&:empty?)
      end
      @tags = []
      if ! params[:tag_id].nil?
        params[:tag_id].reject(&:empty?).each do |id|
          if (id != "")
            @tags.push(id.to_i)
          end
        end
      end
    end


    # 未入力の場合全件が対象
    @properties = Property.all
    # エリア関連の検索処理
    @checkd_areas = []
    if !@areas.blank?
      @properties = @properties.where(area_id: @areas)
      @checkd_areas = @areas
    elsif !@area_groups.blank? && @tags.blank?
      @properties = @properties.where(area_group_id: @area_groups)
      @checkd_areas = Area.where(area_group_id: @area_groups).ids
    end

    if !@tags.blank?
      property_ids = @properties.pluck(:id)
      @tags.each do | tag_id |
        property_ids = Property.joins(:tags).where(id: property_ids).where(tags: {id: tag_id}).pluck(:id)
      end
      @properties = Property.where(id: property_ids)
    end

    # 金額の条件
    if (params[:lower_rent] && !params[:lower_rent].to_i.zero?) && (params[:upper_rent] && !params[:upper_rent].to_i.zero?)#ボッチ演算子
      @properties = @properties.where(rent: params[:lower_rent].to_i..params[:upper_rent].to_i)
    elsif (params[:lower_rent] && params[:lower_rent].to_i.zero?) && (params[:upper_rent] && !params[:upper_rent].to_i.zero?)
      @properties = @properties.where(rent: ..params[:upper_rent].to_i)
    elsif (params[:lower_rent] && !params[:lower_rent].to_i.zero?) && (params[:upper_rent] && params[:upper_rent].to_i.zero?)
      @properties = @properties.where(rent: params[:lower_rent].to_i..)
    end
    @properties_count = @properties.count
    @properties = @properties.page(params[:page]).per(10)

    #検索条件を検索希望一覧画面で表示するため
    @tag_list = Tag.where(id: @tags)
    @area_list = Area.where(id: @areas)
    @area_group_list = AreaGroup.where(id: @area_groups)

    if params[:lower_rent]
      @display_lower_amount =  params[:lower_rent].slice(0,  params[:lower_rent].length - 4)
    end
    if params[:upper_rent]
      @display_upper_amount =  params[:upper_rent].slice(0,  params[:upper_rent].length - 4)
    end

    #再検索用
    @tags=Tag.all

    #キーワード検索の処理
    @keyword = params[:keyword]
    if !@keyword.blank?
      @properties= Property.where("access LIKE ?", "%#{params[:keyword]}%")#モデルでスコープで書く
      .or(Property.where("address LIKE ?", "%#{params[:keyword]}%"))
      .or(Property.where("rent LIKE ?", "%#{params[:keyword]}%"))
      .or(Property.where("property_name LIKE ?", "%#{params[:keyword]}%"))

      @properties_count = @properties.count
      @properties = @properties.page(params[:page]).per(10)

      @checkd_areas = Area.where("area_name LIKE ?", "#{params[:keyword]}%").pluck(:id)
    end
  end

  def index
  end

  def show
    @property=Property.find(params[:id])
    #閲覧履歴
    history = @property.histories.new
    history.user_id = current_user.id
    if current_user.histories.exists?(property_id: "#{params[:id]}")
      old_history = current_user.histories.find_by(property_id: "#{params[:id]}")
      old_history.destroy
    end
    history.save

    @review = Review.new
    @reviews=@property.reviews
    @question = Question.new
    @questions = @property.questions
    @comment = Comment.new
    @comment_comment = CommentComment.new
    @rule = Rule.new
    @rules = @property.rules

    #星評価の平均点を算出
    @avg_score = Review.where(property_id: params[:id]).average(:score)
  end

  def map
    @property=Property.find(params[:property_id])
  end
end

app/controllers/user/questions_controller.rb
class User::QuestionsController < ApplicationController
  before_action :authenticate_user!

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    @question.property_id = params[:property_id]
    @question.checked = false
    if @question.save
      flash[:notice] = "質問の投稿が完了しました!"
    #A物件をレビューしたuser一覧が入っているA物件をレビューした人みんなに通知したいから
      review_users = @question.property.reviews.map{|review| review.user}.uniq
    #レビューしてくれた人一人ひとりにに通知をする処理
      review_users.each do |review_user|
        notification = Notification.new
        notification.action = "review_on_question"
        notification.sender_id = @question.user_id
        notification.receiver_id = review_user.id
        notification.checked = false
        notification.property_id = @question.property_id
        notification.save!
      end
      redirect_to property_path(params[:property_id])
    else
      @property=Property.find(params[:property_id])
      @review = Review.new
      @reviews=@property.reviews
      @questions = @property.questions
      @comment = Comment.new
      @comment_comment = CommentComment.new
      @rule = Rule.new
      @rules = @property.rules
      @avg_score = Review.where(property_id: @property.id).average(:score)
      render 'user/properties/show'
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :relation)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:gender,:age])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    stored_location_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/properties/_error.html.erb
<% if model.errors.any? %>
  <div class="ml-2 text-danger font-weight-bold"><%= model.errors.count %>件のエラーが発生しました</div>
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/user/properties/_review_meter_input.html.erb
<%#入力画面 %>
<div class="col-xl-4">
  <h4 class="mt-5"><%= label %></h4>
  <%= better %>
  <% 5.step(1,-1) do |i| %>
    <%= f.radio_button target, i.to_s %>
  <% end %>
  <%= worth %>
</div>

app/views/user/properties/_tab.html.erb
<div class="wrap mt-5">
  <ul id="tab-menu" class="small-tab-menu">
    <li><a href="#tab1" class="review active">口コミを投稿する</a></li>
    <li><a href="#tab2" class="">口コミを見る</a></li>
    <li><a href="#tab3" class="">質問をする</a></li>
    <li><a href="#tab4" class="qa">Q&A</a></li>
    <li><a href="#tab5" class="">ルールをシェア</a></li>
  </ul>
</div>
<div id="tab-contents" class="tab-conten">
  <div id="tab1" class="tab">
    <%= render '/user/properties/error', model: @review %>
    <%= form_with model: @review, url: property_reviews_path(property_id: @property.id) do |f| %>
      <h2 class="text-center">関係性を選ぶ</h2>
      <div class= "row text-center">
        <div class="col-4 mt-1">
          <%= f.radio_button :relation, Review.relations.key(0) %>
          <%= f.label :relation, Review.relations_i18n[:resident] %><br>
        </div>
        <div class="col-4">
          <%= f.radio_button :relation, Review.relations.key(1) %>
          <%= f.label :relation, Review.relations_i18n[:former_resident] %><br>
          <%= f.select :relation_detail1, [['2022年頃まで','twenty_two'], ['2021年頃まで','twenty_one'], ['2020年頃まで','twenty'], ['2019年頃まで','nineteen'], ['2018年頃まで','eighteen'], ['2018年より前','before_that']],{prompt: '選択してください'} %>
        </div>
          <!--モデルが関連している選択ボックス (2行目)&データベースから取ってきてないからこの書き方でいいデータベースから取ってきてたらnagano_cakeのやり方-->
        <div class="col-4">
          <%= f.radio_button :relation, Review.relations.key(2) %>
          <%= f.label :relation, Review.relations_i18n[:others] %><br>
          <%= f.select :relation_detail2, [['入居検討者','kentosya'], ['入居予定者','yoteisya'], ['周辺住人','syuhenjunin'], ['住人の知人','chizin'], ['大家さん','oya'], ['不動産関係者','kankeisya'], ['その他','sonota']],{prompt: '選択してください'} %>
        </div>
      </div>

      <h2 class=" text-center mt-5">総合評価</h2>
      <div class="text-center">
        <div id="post_raty"></div>
      </div>

      <div class= "row text-center">
        <%= render '/user/properties/review_meter_input',label: "住民の雰囲気", better: "良い", f: f, worth: "良くない",target: :atmosphere %>
        <%= render '/user/properties/review_meter_input',label: "住人同士の距離感", better: "親しい", f: f, worth: "あいさつ程度",target: :distance_sense %>
        <%= render '/user/properties/review_meter_input',label: "騒音", better: "静か", f: f, worth: "騒がしい",target: :noise %>
        <%= render '/user/properties/review_meter_input',label: "共有部の清潔さ", better: "清潔", f: f, worth: "不衛生",target: :cleanliness_shared %>
        <%= render '/user/properties/review_meter_input',label: "水回りの混雑具合", better: "常に使える", f: f, worth: "混雑している",target: :congestion_shared %>
        <%= render '/user/properties/review_meter_input',label: "ネット速度", better: "速い", f: f, worth: "遅い",target: :net_speed %>
        <%= render '/user/properties/review_meter_input',label: "シャワーの水圧", better: "強い", f: f, worth: "弱い",target: :shower %>
        <%= render '/user/properties/review_meter_input',label: "交流会やパーティー", better: "頻繁にある", f: f, worth: "少ない",target: :event %>
      </div>

      <div class="text-center mt-5">
        <h3>タイトル<span class="h6">(1~100文字)</span></h3>
        <%= f.text_field :title,:size=>"43x10" %>
        <h3 class="mt-3">本文<span class="h6">(7文字~1000文字)</span></h3>
        <%= f.text_area :body,:size=>"43x10" %>
      </div>

      <div class="text-center mt-3">
        <h6>住み続けたい?</h6>
        <%= f.radio_button :repeat,'3' %>はい
        <%= f.radio_button :repeat,'1' %>いいえ
        <%= f.radio_button :repeat,'2' %>わからない
      </div>

      <div class="text-center mt-3">
        <%= f.submit"投稿する",class: "btn" %>
      </div>
    <% end %>
  </div>

  <div id="tab2" class="tab">
    <% if @reviews.present? %>
      <div class="mb-5">
        <h5 class="mb-5">全<%= @reviews.count %>件</h5>
        <h3>総合評価</h3>
        <div class="mb-5">
          <div id="show_raty" data-avg-score=<%= @avg_score %> ></div>
        </div>
      </div>
    <% else %>
      <div class="mb-5">
        <h6>レビューがありません</h6>
      </div>
    <% end %>
    <% @reviews.each do |review| %>
      <div class="row">
        <div class="col-xl-5 col-5">
          <h4 class="writing"><%= review.title %></h4>
        </div>
        <div class="col-xl-2 col-5">
          <% if review.repeat == "3" %>
            <p class="bg-danger text-white text-center rounded-pill small mb-5 mt-1">住み続けたい</p>
          <% end %>
        </div>
      </div>
      <p class="mt-2 mb-4 writing"><%= review.body %></p>
      <%= render '/user/properties/review', review: review %>
      <div class="review-name mt-3">
        <%= review.user.nickname %>
        <% unless review.user.gender == "非公開" %>
          <%= review.user.gender %>
        <% end %>
        <% unless review.user.age == "非公開" %>
          <%= review.user.age %>
        <% end %>
        <%= review.relation_i18n %>
        <% if review.relation_detail_i18n != "Now resident" %>
          <%= review.relation_detail_i18n %>
        <% end %>
        <%= review.created_at.to_s(:datetime_jp) %>
      </div>
    <% end %>
  </div>

  <div id="tab3" class="tab">
    <%= render '/user/properties/error', model: @question %>
    <div class="text-center">
      <%= form_with model: @question, url:  property_questions_path(property_id: @property.id) do |f| %>
        <h3>タイトル<span class="h6">(1~100文字)</span></h3>
        <%= f.text_field :title,:size=>"43x10" %>
        <h3 class="mt-3">本文<span class="h6">(7~1000文字)</span></h3>
        <%= f.text_area :body,:size=>"43x10" %></br>
        <div class="mb-3">
          <%= f.select :relation, [['住人','resident'],['元住人','former_resident'],['入居検討者','kentosya'], ['入居予定者','yoteisya'], ['周辺住人','syuhenjunin'], ['住人の知人','chizin'], ['大家さん','oya'], ['不動産関係者','kankeisya'], ['その他','sonota']],{prompt: '選択してください'} %><br>
        </div>
        <%= f.submit "投稿する",class: "btn" %>
      <% end %>
    </div>
  </div>

  <div id="tab4" class="tab">
    <%= render '/user/properties/error', model: @comment %>
    <%= render '/user/properties/error', model: @comment_comment %>
    <% if @questions.present? %>
      <h5 class="ml-1">全<%= @questions.count %>件</h5>
      <% @questions.each do |question| %>
        <%= render '/user/properties/question', question: question, comment: @comment, comment_comment: @comment_comment %>
      <% end %>
    <% else %>
      <h6 class="mt-4">質問がありません</h6>
    <% end %>
  </div>

  <div id="tab5" class="tab">
    <%= render '/user/properties/error', model: @rule %>
    <div class="rule-form small-rule-form">
      <h3>ハウスルールをシェアする</h3>
      <p class="mb-3">※なるべく下記のハウスルールリストにまだ書かれていないことをご記入ください</p>
      <%= form_with model: @rule, url:  property_rules_path(property_id: @property.id) do |f| %>
        <%= f.text_area :body ,:size=>"35x7" %>
        <%= f.submit 'シェアする',class: "btn" %>
      <% end %>
    </div>
    <div class="rule rule01 small-rule mt-5">
      <h3 class="text-center font-weight-bold mb-4">ハウスルール</h3>
      <% @rules.each do |rule| %>
        <p class="writing mb-3">• <%= rule.body %></p>
      <% end %>
    </div>
  </div>
</div>

<script>
// RailsのデータをJSにセットする #ここでは質問数をセット
const qLength = "<%= @questions.length %>"
// クラス名が[Q&A]のDOM要素を取得
const tab4 = document.getElementsByClassName("Q&A")[0]
// 質問があった場合あテキストカラーを変更する
if(qLength !== "0") {
  tab4.style.color ="red"
}
// テキストを追加する
tab4.textContent += "(" + qLength + ")"
</script>

<script>
// raty.jsの初期化
window.raty = function(elem,opt) {
    if (elem == null) return;
    let raty =  new Raty(elem,opt)
    raty.init();
    return raty;
}

Rails.start()
ActiveStorage.start()
</script>

app/views/user/properties/seach.html.erb
<%#binding.pry%>
<%@properties.each do |property|%>
  <h2><%=property.property_name%></h2>
  <%=property.access%>
  <%=image_tag property.image%>
  <table>
    <tr><th>賃料</th><td><%=property.rent%></td></tr>
    <tr><th>住所</th><td><%=property.address%></td></tr>
    <tr><th>アクセス</th><td><%=property.access%></td></tr>
    <tr><th>入居条件</th><td><%=property.condition%></tds></tr>
    <tr><th>空室</th></th><td><%=property.vacancy%></td></tr>
    <tr><th>特徴</th></th><td><%property.tags.each do |tag|%><%=tag.name%><%end%></td></tr>
   <%if user_signed_in? %>
     <%=link_to "詳細を見る",property_path(property.id)%>
   <%else%>
     <%= link_to new_user_registration_path do %>
     詳細を見る
     <%end%>
  <%end%>

  </table>
    <%#binding.pry%>
  <%if user_signed_in? %>
    <% if property.favorited_by?(current_user) %>
        <%= link_to property_favorites_path(property.id, 1), method: :delete do %>
          ♥<%= property.favorites.count %> お気に入り
        <% end %>
    <% else %>
          <%= link_to property_favorites_path(property.id), method: :post do %>
          ♡<%= property.favorites.count %> お気に入り
        <% end %>
    <% end %>
  <%else%>
     <%= link_to new_user_registration_path do %>
     ♡<%= property.favorites.count %> お気に入り
     <%end%>
  <%end%>
<%end%>